apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prefect-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: example77.test
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svc-prefect
                port:
                  number: 4200




