apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
#    - 198.13.62.143/32
    - {{ .Values.NODE.IP }}/32
#    - fc00:f853:0ccd:e799::/124

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2adt
  namespace: metallb-system
spec:
  ipAddressPools:
    - first-pool
