apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config
  namespace: dev
data:
  POSTGRES_USER: "{{ .Values.POSTGRES.POSTGRES_USER }}"
  POSTGRES_PASSWORD: "{{ .Values.POSTGRES.POSTGRES_PASSWORD }}"
  POSTGRES_HOST: "{{ .Values.POSTGRES.POSTGRES_HOST }}"
  PGPORT: "{{ .Values.POSTGRES.PGPORT }}"
  POSTGRES_DB: "{{ .Values.POSTGRES.POSTGRES_DB }}"
  POSTGRES_DEFAULT_DB: "{{ .Values.POSTGRES.POSTGRES_DEFAULT_DB }}"
  TZ: "Asia/Taipei"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-pg
  namespace: dev
spec:
  selector: #
    app: pg
  type: NodePort
  ports:
    - port: 5432 #service port
      protocol: TCP
      targetPort: 5432  #pod port
      nodePort: 30002 # 可不指定 會預設自動分配於 30000-32767之間

---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: st-pg
  namespace: dev
spec:
  serviceName: "svc-pg"
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
        - name: pg
          image: y40103/mingde_pg:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: pg-config
          lifecycle:
            postStart:
              exec:
                command:
                  - bash
                  - /src/run.sh
            
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-claim
  namespace: dev
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: pg
